org.gradle.jvmargs=-Xmx1024m -Xms256m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseSerialGC
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
