package com.example.core.ffmpeg

import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.arthenica.ffmpegkit.FFmpegKit
import com.arthenica.ffmpegkit.FFmpegKitConfig
import com.arthenica.ffmpegkit.FFmpegSession
import com.arthenica.ffmpegkit.ReturnCode
import java.io.File
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.FixMethodOrder
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.MethodSorters

/**
 * Native runtime proof for the maintained FFmpegKit engine on the packaged ABI.
 *
 * This test deliberately avoids fixtures and network access: every input is generated by
 * FFmpeg's own lavfi sources, so the only thing under test is whether the native engine
 * shipped in the APK actually loads and runs on the device executing this suite.
 *
 * Failure surface (any of these must fail the test, never be swallowed):
 * UnsatisfiedLinkError, dlopen failed, library not found, wrong ELF class,
 * missing native dependency, FFmpeg process failure.
 */
@RunWith(AndroidJUnit4::class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class FFmpegNativeSmokeTest {

    private companion object {
        const val TAG = "FFmpegNativeSmoke"

        /** Roughly one second of synthetic video keeps the test fast on low-end devices. */
        const val SYNTHETIC_DURATION_SECONDS = "1"
        const val SYNTHETIC_SIZE = "128x128"
        const val SYNTHETIC_FPS = "15"

        /**
         * Substrings that indicate the native library could not be loaded or does not match the
         * device ABI. These are matched against FFmpegKit output and thrown-exception messages.
         */
        val NATIVE_FAILURE_MARKERS = listOf(
            "unsatisfiedlinkerror",
            "dlopen failed",
            "library not found",
            "wrong elf class",
            "cannot locate symbol",
            "is 32-bit instead of 64-bit",
            "is 64-bit instead of 32-bit",
            "has unexpected e_machine"
        )

        /**
         * Encoders the app's command builders could legitimately target for an H.264/MP4 result.
         * Presence is decided by runtime `-encoders` output only, never by package documentation.
         */
        val H264_CANDIDATE_ENCODERS = listOf(
            "libx264",
            "libopenh264",
            "h264_mediacodec",
            "h264_v4l2m2m"
        )
    }

    private val outputDir: File by lazy {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        File(context.cacheDir, "ffmpeg-smoke").apply { mkdirs() }
    }

    /** A: the native engine must load and report a version before anything else is attempted. */
    @Test
    fun a_nativeEngineLoadsAndReportsVersion() {
        val version = try {
            FFmpegKitConfig.getFFmpegVersion()
        } catch (t: Throwable) {
            failOnNativeError("FFmpegKitConfig.getFFmpegVersion()", t)
        }

        Log.i(TAG, "FFmpeg version reported by native engine: $version")
        assertNotNull("Native engine returned a null FFmpeg version", version)
        assertTrue("Native engine returned a blank FFmpeg version", version!!.isNotBlank())
    }

    /** B + C: `-version` must run through the real native process and exit successfully. */
    @Test
    fun b_versionCommandExecutesSuccessfully() {
        val session = runFFmpeg("-version")
        val output = session.allLogsAsString.orEmpty()

        Log.i(TAG, "ffmpeg -version exit=${session.returnCode} output=\n$output")
        assertNativeErrorFree("ffmpeg -version", output)
        assertSuccess("ffmpeg -version", session)
        assertTrue(
            "`-version` output did not contain an ffmpeg version banner",
            output.contains("ffmpeg version", ignoreCase = true)
        )
    }

    /**
     * D + E: query the encoder table at runtime and record what the shipped binary really has.
     *
     * The recorded inventory is the only acceptable input for deciding which encoder the app's
     * FFmpeg command builders may use.
     */
    @Test
    fun c_encoderInventoryIsQueryableAndContainsAnH264Encoder() {
        val session = runFFmpeg("-hide_banner", "-encoders")
        val output = session.allLogsAsString.orEmpty()

        assertNativeErrorFree("ffmpeg -encoders", output)
        assertSuccess("ffmpeg -encoders", session)

        val encoderNames = parseEncoderNames(output)
        assertTrue("`-encoders` returned no parsable encoder entries", encoderNames.isNotEmpty())

        val videoEncoders = parseEncoderNames(output, videoOnly = true)
        val availableH264 = H264_CANDIDATE_ENCODERS.filter { it in encoderNames }

        val inventory = buildString {
            appendLine("ffmpeg version: ${FFmpegKitConfig.getFFmpegVersion()}")
            appendLine("total encoders: ${encoderNames.size}")
            appendLine("video encoders (${videoEncoders.size}): ${videoEncoders.sorted().joinToString(", ")}")
            appendLine("h264-capable candidates present: ${availableH264.joinToString(", ").ifEmpty { "NONE" }}")
            appendLine()
            appendLine("--- raw -encoders output ---")
            append(output)
        }
        val inventoryFile = File(outputDir, "encoder-inventory.txt").apply { writeText(inventory) }
        Log.i(TAG, "Encoder inventory written to ${inventoryFile.absolutePath}")
        Log.i(TAG, "Video encoders: ${videoEncoders.sorted().joinToString(", ")}")
        Log.i(TAG, "H.264-capable encoders present: ${availableH264.joinToString(", ").ifEmpty { "NONE" }}")

        assertTrue(
            "No H.264-capable encoder found at runtime. Checked ${H264_CANDIDATE_ENCODERS.joinToString(", ")}. " +
                "Available video encoders: ${videoEncoders.sorted().joinToString(", ")}",
            availableH264.isNotEmpty()
        )
    }

    /**
     * F + G + H + I: encode a short synthetic clip with an encoder proven present at runtime,
     * verify the artifact, then probe it when the FFprobe API is available.
     */
    @Test
    fun d_syntheticEncodeProducesPlayableOutput() {
        val encoder = firstAvailableH264Encoder()
            ?: run {
                fail("No H.264-capable encoder available at runtime; cannot verify a real encode")
                return
            }
        Log.i(TAG, "Encoding synthetic clip with runtime-verified encoder: $encoder")

        val output = File(outputDir, "smoke-$encoder.mp4")
        if (output.exists()) output.delete()

        val args = mutableListOf(
            "-hide_banner",
            "-y",
            "-f", "lavfi",
            "-i", "testsrc=size=$SYNTHETIC_SIZE:rate=$SYNTHETIC_FPS",
            "-t", SYNTHETIC_DURATION_SECONDS,
            "-c:v", encoder
        )
        // -preset is an x264/openh264-family option; hardware encoders reject it outright.
        if (encoder == "libx264" || encoder == "libopenh264") {
            args += listOf("-preset", "ultrafast")
        }
        args += listOf("-pix_fmt", "yuv420p", output.absolutePath)

        val session = runFFmpeg(*args.toTypedArray())
        val logs = session.allLogsAsString.orEmpty()
        Log.i(TAG, "Synthetic encode exit=${session.returnCode} output=\n$logs")

        assertNativeErrorFree("synthetic encode", logs)
        assertSuccess("synthetic encode with $encoder", session)
        assertTrue("Encoder $encoder did not create ${output.absolutePath}", output.exists())
        assertTrue("Encoder $encoder produced an empty file", output.length() > 0L)
        Log.i(TAG, "Synthetic output: ${output.absolutePath} (${output.length()} bytes)")

        probeIfAvailable(output)
    }

    // --- helpers -------------------------------------------------------------------------------

    private fun runFFmpeg(vararg args: String): FFmpegSession =
        try {
            FFmpegKit.executeWithArguments(args)
        } catch (t: Throwable) {
            failOnNativeError("ffmpeg ${args.joinToString(" ")}", t)
            throw t
        }

    private fun assertSuccess(label: String, session: FFmpegSession) {
        if (!ReturnCode.isSuccess(session.returnCode)) {
            fail(
                "$label failed: returnCode=${session.returnCode} state=${session.state} " +
                    "failStackTrace=${session.failStackTrace} logs=${session.allLogsAsString}"
            )
        }
    }

    private fun assertNativeErrorFree(label: String, output: String) {
        val lowered = output.lowercase()
        NATIVE_FAILURE_MARKERS.firstOrNull { lowered.contains(it) }?.let { marker ->
            fail("$label reported a native loading/ABI error containing \"$marker\": $output")
        }
    }

    private fun failOnNativeError(label: String, t: Throwable): Nothing {
        val detail = "${t::class.java.name}: ${t.message}"
        fail("$label threw before completing, indicating a native loading/ABI problem: $detail")
        throw AssertionError(detail, t)
    }

    private fun firstAvailableH264Encoder(): String? {
        val session = runFFmpeg("-hide_banner", "-encoders")
        val output = session.allLogsAsString.orEmpty()
        assertNativeErrorFree("ffmpeg -encoders", output)
        assertSuccess("ffmpeg -encoders", session)
        val names = parseEncoderNames(output)
        return H264_CANDIDATE_ENCODERS.firstOrNull { it in names }
    }

    /**
     * `-encoders` rows look like " V....D libx264   H.264 ...", where the first token is a
     * capability flag block whose first character is the media type.
     */
    private fun parseEncoderNames(output: String, videoOnly: Boolean = false): Set<String> =
        output.lineSequence()
            .mapNotNull { line ->
                val trimmed = line.trim()
                val parts = trimmed.split(Regex("\\s+"))
                if (parts.size < 2) return@mapNotNull null
                val flags = parts[0]
                if (flags.length != 6) return@mapNotNull null
                if (videoOnly && flags[0] != 'V') return@mapNotNull null
                if (!videoOnly && flags[0] !in charArrayOf('V', 'A', 'S')) return@mapNotNull null
                parts[1].takeIf { it.isNotBlank() && it != "=" }
            }
            .toSet()

    /**
     * H: probing is optional because the FFprobe API is a separate class in some distributions.
     * Reflection keeps the test compilable and honest either way, and a present-but-failing
     * probe is still treated as a failure.
     */
    private fun probeIfAvailable(output: File) {
        val probeClass = try {
            Class.forName("com.arthenica.ffmpegkit.FFprobeKit")
        } catch (_: ClassNotFoundException) {
            Log.i(TAG, "FFprobeKit not present in this distribution; skipping probe step")
            return
        }

        val method = probeClass.methods.firstOrNull {
            it.name == "getMediaInformation" && it.parameterTypes.size == 1 &&
                it.parameterTypes[0] == String::class.java
        }
        if (method == null) {
            Log.i(TAG, "FFprobeKit.getMediaInformation(String) unavailable; skipping probe step")
            return
        }

        val session = try {
            method.invoke(null, output.absolutePath)
        } catch (t: Throwable) {
            failOnNativeError("FFprobeKit.getMediaInformation", t)
        }
        assertNotNull("FFprobe returned a null session for ${output.absolutePath}", session)

        val info = session!!.javaClass.getMethod("getMediaInformation").invoke(session)
        assertNotNull("FFprobe could not read media information from ${output.absolutePath}", info)

        val duration = info!!.javaClass.getMethod("getDuration").invoke(info) as? String
        Log.i(TAG, "FFprobe reported duration=$duration for ${output.name}")
        assertTrue(
            "FFprobe reported a non-positive duration ($duration) for the synthetic output",
            (duration?.toDoubleOrNull() ?: 0.0) > 0.0
        )
    }
}
